Feature/ppa002
Ayato-kosaka/spelieve pull request #326
Opened 2022-11-15 13:17 UTC by Takapy1

@Ayato-kosaka 
tsc, eslint辺りも修正したから、明日あたりにレビューお願いします〜
Elastic Search調べ始めるわ

2022-11-15 13:52 UTC, Takapy1 commented
それ以外明後日了解した！

2022-11-15 13:53 UTC, Ayato-kosaka commented
@Takapy1 
今日develop掃除した！
https://github.com/Ayato-kosaka/spelieve/pull/325#issuecomment-1315247676
通知届いてなかったか、、

2022-11-15 14:06 UTC, Takapy1 commented
@Ayato-kosaka 
そゆことか！お掃除ありがとう

2022-11-18 01:39 UTC, Takapy1 commented
@Ayato-kosaka 
昨日の修正部分を直しました
ESlintの以下のエラーだけ直せない状態だからレビューとともに、少しみて欲しい
```
/.../spelieve/src/Place/Endpoint/PlaceHttpPost.ts
  7:28  error  Promise returned in function argument where a void return was expected  @typescript-eslint/no-misused-promises
  7:28  error  Promise executor functions should not be async                          no-async-promise-executor

/.../spelieve/src/Place/Pages/PPA002Place/Place.tsx
  22:10  error  Variable name `place_id` must match one of the following formats: camelCase, PascalCase, UPPER_CASE  @typescript-eslint/namin
```

2022-11-19 16:50 UTC, Ayato-kosaka commented
tsc error
```
gitpod /workspace/spelieve (feature/PPA002) $ npx tsc
src/Place/Models/PDB01MPlace/Contexts/PCT012MPlaceOne/MPlaceOne.tsx:82:16 - error TS2322: Type 'MPlaceOneInterface' is not assignable to type 'MPlace'.
  Types of property 'openingHours' are incompatible.
    Type 'string | [string, string][]' is not assignable to type 'MPlaceOpeningHoursInterface[] | undefined'.
      Type 'string' is not assignable to type 'MPlaceOpeningHoursInterface[]'.

82      (data) => data,
                  ~~~~

  node_modules/spelieve-common/lib/Utils/FirestoreConverter.d.ts:4:44
    4 }, fromModel: (data: model) => T, toModel: (data: T) => model) => FirestoreDataConverter<T>;
                                                 ~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.

src/Place/Pages/PPA002Place/PlaceController.ts:14:24 - error TS2322: Type '{ place_id: string; placeName: string; }' is not assignable to type 'PlacesPropsInterface | PlacePropsInterface | undefined'.
  Object literal may only specify known properties, and 'placeName' does not exist in type 'PlacesPropsInterface | PlacePropsInterface'.

14    params: { place_id, placeName },
                          ~~~~~~~~~

  node_modules/@react-navigation/core/lib/typescript/src/types.d.ts:491:5
    491     params?: never;
            ~~~~~~
    The expected type comes from property 'params' which is declared here on type 'NavigatorScreenParams<PlaceStackParamList, Readonly<{ key: string; index: number; routeNames: string[]; history?: unknown[] | undefined; routes: NavigationRoute<ParamListBase, string>[]; type: string; stale: false; }>>'


Found 2 errors in 2 files.

Errors  Files
     1  src/Place/Models/PDB01MPlace/Contexts/PCT012MPlaceOne/MPlaceOne.tsx:82
     1  src/Place/Pages/PPA002Place/PlaceController.ts:14
```

2022-11-19 19:57 UTC, Ayato-kosaka requested changes
@Takapy1 
遅くなって申し訳ない！
全部レビューしました！
大体いい感じやったし、モンキーテストもしながらレビューしたから、今回の修正でクローズ出来ると思う！

2022-11-19 19:57 UTC, Ayato-kosaka commented on src/Place/Pages/PPA002Place/PlaceController.ts
> +export const PPA002PlaceController = ({ place_id, language }: PlacePropsInterface): PlaceControllerInterface => {
PlacePropsInterface から削除したから修正お願い！
```suggestion
export const PPA002PlaceController = ({ place_id }: PlacePropsInterface): PlaceControllerInterface => {
```

2022-11-19 19:57 UTC, Ayato-kosaka commented on src/Place/Pages/PPA002Place/PlaceController.ts
> +		});
まだ固まってないから、TODOコメント付けておいて〜
```suggestion
		// TODO: https://github.com/Ayato-kosaka/spelieve/issues/335 Itinerary 新規作成 
		// navigation.navigate('Itinerary', {
		// 	screen: 'ItineraryTopTabNavigator',
		// 	params: { place_id, placeName },
		// });
```

2022-11-19 19:57 UTC, Ayato-kosaka commented on src/Place/Pages/PPA002Place/Place.tsx
> +	}, [place_id, setPlaceID]);
useEffect は Controller に移動してください

2022-11-19 19:57 UTC, Ayato-kosaka commented on src/Place/Pages/PPA002Place/Place.tsx
> +					<PMC01203PlaceImage />
これは、なんでコンポーネント切り出してるの？？
FuncListにもないから、切り出すならスプレッドシートに追加してほしい！

2022-11-19 19:57 UTC, Ayato-kosaka commented on src/Place/Pages/PPA002Place/Place.tsx
> +import TimeIcon from 'react-native-vector-icons/Ionicons';
https://github.com/Ayato-kosaka/spelieve/wiki/%E5%88%A9%E7%94%A8Componet#icon
で利用コンポーネントの統一化の整理してるんだけど、Icon はMaterialCommunityIconsを使ってほしい。
```suggestion
import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';
```

2022-11-19 19:57 UTC, Ayato-kosaka commented on src/Place/Pages/PPA002Place/PlaceController.ts
> +	const onCreateItineraryClicked = (placeName: string) => {
Controller から、useContext で place  よべるから引数の placeName 必要ないと思うけど、時間ないから修正に時間掛かりそうだったらこのままでも :ok_man:

2022-11-19 19:57 UTC, Ayato-kosaka commented on src/Place/Pages/PPA002Place/Place.tsx
> +								// eslint-disable-next-line
eslint-disable-next-line はどのESLintに対するものか明記してほしい
```suggestion
								// eslint-disable-next-line @typescript-eslint/no-floating-promises
```

2022-11-19 19:57 UTC, Ayato-kosaka commented on src/Place/Pages/PPA002Place/Place.tsx
> +					</WebIcon>
website 無ければ非表示で良いと思うけどどうかな
```suggestion
					{place.website && (
						<WebIcon name="web" size={20}>
							<Text
								style={styles.urlLink}
								onPress={() => {
									// eslint-disable-next-line @typescript-eslint/no-floating-promises
									Linking.openURL(place.website!);
								}}>
								{place.website}
							</Text>
						</WebIcon>
					)}
```

2022-11-19 19:57 UTC, Ayato-kosaka commented on src/Place/Pages/PPA002Place/Place.tsx
> +					</FetherIcon>
formatted_phone_number 無ければ非表示で良いと思うけどどうかな
あと、クリックで電話掛けれるようにしてほしい！
```suggestion
					{place.formatted_phone_number && (
						<FetherIcon name="phone-call" size={20}>
							<Text
								style={styles.infoText}
								onPress={() => {
									// eslint-disable-next-line @typescript-eslint/no-floating-promises
									Linking.openURL(`tel:${place.formatted_phone_number!}`);
								}}>
								{place.formatted_phone_number}
							</Text>
						</FetherIcon>
					)}
```

2022-11-19 19:57 UTC, Ayato-kosaka commented on src/Place/Pages/PPA002Place/Place.tsx
> +						</Text>
GoogleMapでReviewとか写真とかの個別リンクとれなさそうだから、
Review の下に 「see more info at Google Map」
画像の下に「show more」
だけにして、ここはなしでいいや
```suggestion
```

2022-11-19 19:57 UTC, Ayato-kosaka commented on src/Place/Pages/PPA002Place/Place.tsx
> +					/>
ここは、「see more info at Google Map」にして〜
```suggestion
					<Text
						style={styles.urlLink}
						onPress={() => {
							// eslint-disable-next-line
							Linking.openURL(`${place.mapUrl}`);
						}}
					>
					{i18n.t('see more info at Google Map')}
					</Text>
```

2022-11-19 19:57 UTC, Ayato-kosaka commented on src/Place/Pages/PPA002Place/Place.tsx
> +					/>
ここは、「see more」にして〜
```suggestion
					<Text
						style={styles.urlLink}
						onPress={() => {
							// eslint-disable-next-line
							Linking.openURL(`${place.mapUrl}`);
						}}>
						{i18n.t('see more')}
					</Text>
```

2022-11-19 20:02 UTC, Ayato-kosaka commented on src/Place/Pages/PPA002Place/Place.tsx
> +import TimeIcon from 'react-native-vector-icons/Ionicons';
https://github.com/Ayato-kosaka/spelieve/blob/f97851ae56ea987121dbcede20e377fe939ce9b6/src/Itinerary/Navigator/INV002ItineraryTopTabNavigator/ItineraryTopTabNavigator.tsx#L40
こことか参考になると思う！

2022-11-20 15:39 UTC, Ayato-kosaka commented
@Takapy1 
https://github.com/Ayato-kosaka/spelieve/blob/d7ca1a62ae6c90d8b9ed845c65f90c9dc8ee11c5/src/Place/Pages/PPA002Place/Place.tsx#L45-L124
指摘漏れてたけど、↑PMC01202PlaceInformation に切り出してほしい！
Itineraryのplan editでつかうから

2022-11-23 02:43 UTC, Takapy1 commented on src/Common/Hooks/i18n-js/Lang.ts
> +// import { LangIf } from './LangIf';
@Ayato-kosaka 
[0887caf](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/0887caf5d4b6dae6c281e6a9439f3830cbd085fe)で対応

2022-11-23 02:43 UTC, Takapy1 commented on src/Common/Hooks/i18n-js/index.ts
> +// import Lang from './Lang';
@Ayato-kosaka 
[0887caf](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/0887caf5d4b6dae6c281e6a9439f3830cbd085fe)で対応

2022-11-23 02:43 UTC, Takapy1 commented on src/Common/Hooks/i18n-js/index.ts
> +// export const i18nLang = Lang;
[0887caf](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/0887caf5d4b6dae6c281e6a9439f3830cbd085fe)で対応

2022-11-23 02:46 UTC, Takapy1 commented on src/Place/Models/PDB01MPlace/Contexts/PCT012MPlaceOne/MPlaceOne.tsx
> +						setPlace(undefined);
[4b64a5d](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/4b64a5d3a2175302f82f5f359e12f1e76ea06dda)対応

2022-11-23 02:49 UTC, Takapy1 commented on src/Place/Models/PDB01MPlace/Contexts/PCT012MPlaceOne/MPlaceOne.tsx
> +	}, [collectionRef, placeID, language, isLoading]);
[bc74cc0](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/bc74cc0943722d6d84dbf277821d443d9f766aed)

2022-11-23 02:57 UTC, Takapy1 commented on src/Place/Models/PDB01MPlace/Contexts/PCT012MPlaceOne/MPlaceOne.tsx
> +				querySnap = await getDocs(q);
[ea8890c](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/ea8890cee1cd9e126c335df27bd4778cadd480aa)

2022-11-23 02:59 UTC, Takapy1 commented on src/Place/Models/PDB01MPlace/Contexts/PCT012MPlaceOne/MPlaceOne.tsx
> +				querySnap = await getDocs(q);
@Ayato-kosaka 
上のsuggestion取り込むと、行が被ってこのsuggestionを取り込めなくなったから、
手修正してます。確認お願い。

2022-11-23 02:59 UTC, Takapy1 commented on src/Place/Models/PDB01MPlace/Contexts/PCT012MPlaceOne/MPlaceOne.tsx
> +			setPlace(querySnap.docs[0].data());
[10ab250](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/10ab250e2b39e26c69f098df742c0a5a6f5203c1)

2022-11-23 03:03 UTC, Takapy1 commented on src/Place/Endpoint/PlaceHttpPost.ts
> +	});
[ea8890c](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/ea8890cee1cd9e126c335df27bd4778cadd480aa)

2022-11-23 03:07 UTC, Takapy1 commented on src/Place/Models/PDB01MPlace/Contexts/PCT012MPlaceOne/MPlaceOne.tsx
> +					(data) => data,
[c947ac5](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/c947ac5ccf2ae62aee0e2b8d922786c26006d3b2)

2022-11-23 03:11 UTC, Takapy1 commented on src/Place/Pages/PPA002Place/Place.tsx
> +	// TODO: https://github.com/Ayato-kosaka/spelieve/issues/321 存在しないplace_idはずっとローディング
[6737551](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/6737551df256d731f318d926cc1cf97563803c29)

2022-11-23 03:11 UTC, Takapy1 commented on src/Place/Pages/PlacePageNavigator/PlacePageNavigator.web.tsx
> +
[8a8883b](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/8a8883b704fa89c74277267a78fca43decf3e7ec)

2022-11-23 03:16 UTC, Takapy1 commented on src/Place/Pages/PPA002Place/Place.tsx
> +	const { place_id, language } = route.params;
[39d3ec3](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/39d3ec32d8f44545b7b9638473a24f6628061897)
[e70e2e2](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/e70e2e20900ed4174e950bcf2c709b1ed7609d70)で対応

2022-11-23 03:18 UTC, Takapy1 commented on src/Place/Pages/PPA002Place/PlaceController.ts
> +export const PPA002PlaceController = ({ place_id, language }: PlacePropsInterface): PlaceControllerInterface => {
[3dcf661](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/3dcf6619e1529e2f42f42e2b6b7402c72fa12097)

2022-11-23 03:19 UTC, Takapy1 commented on src/Place/Pages/PPA002Place/PlaceController.ts
> +		});
[624d7d0](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/624d7d096dcd4b5bdd7e6b74fa9967b72dcf684b)

2022-11-23 03:22 UTC, Takapy1 commented on src/Place/Pages/PPA002Place/Place.tsx
> +	}, [place_id, setPlaceID]);
[ef58f09](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/ef58f09d0f42fedeca2e4e74a404c9b753d06ce9)

2022-11-23 03:29 UTC, Takapy1 commented on src/Place/Pages/PPA002Place/Place.tsx
> +					<PMC01203PlaceImage />
[bc76ce2](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/bc76ce2bba51490b1baaba4451fafd4cd80f13dd)
切り出す理由なさそうなので、削除しました

2022-11-23 04:06 UTC, Takapy1 commented on src/Place/Pages/PPA002Place/Place.tsx
> +import TimeIcon from 'react-native-vector-icons/Ionicons';
[f654a03](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/f654a037111b1f116bc7d25354c6cb37b6ca3005)

2022-11-23 04:12 UTC, Takapy1 commented on src/Place/Pages/PPA002Place/PlaceController.ts
> +	const onCreateItineraryClicked = (placeName: string) => {
[ebf0599](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/ebf0599f88a9b3255e51593945b7275ac8c2d9a4)で対応
PG_DATA修正済み

2022-11-23 04:16 UTC, Takapy1 commented on src/Place/Pages/PPA002Place/Place.tsx
> +								// eslint-disable-next-line
[2e91475](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/2e9147568978db67fe498f98ce247a5373f24b25)

2022-11-23 04:20 UTC, Takapy1 commented on src/Place/Pages/PPA002Place/Place.tsx
> +					</WebIcon>
[a02221c](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/a02221c7c9b09ce31eda8fb286a8a6136b01700a)

2022-11-23 04:24 UTC, Takapy1 commented on src/Place/Pages/PPA002Place/Place.tsx
> +					</FetherIcon>
[f9e4862](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/f9e4862ecb7d610ab18a622c81c8c12f92b63eb9)

2022-11-23 04:32 UTC, Takapy1 commented on src/Place/Pages/PPA002Place/Place.tsx
> +						</Text>
[0d1ac72](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/0d1ac720beaa772a689ec621fe0386c5928cf4d0)

2022-11-23 04:32 UTC, Takapy1 commented on src/Place/Pages/PPA002Place/Place.tsx
> +					/>
[0d1ac72](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/0d1ac720beaa772a689ec621fe0386c5928cf4d0)

2022-11-23 04:32 UTC, Takapy1 commented on src/Place/Pages/PPA002Place/Place.tsx
> +					/>
[0d1ac72](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/0d1ac720beaa772a689ec621fe0386c5928cf4d0)

2022-11-23 04:59 UTC, Takapy1 commented
> @Takapy1
> 
> https://github.com/Ayato-kosaka/spelieve/blob/d7ca1a62ae6c90d8b9ed845c65f90c9dc8ee11c5/src/Place/Pages/PPA002Place/Place.tsx#L45-L124
> 
> 
> 指摘漏れてたけど、↑PMC01202PlaceInformation に切り出してほしい！
> Itineraryのplan editでつかうから

[1a4b26b](https://github.com/Ayato-kosaka/spelieve/pull/326/commits/1a4b26b9cf8248db9c9f9d5d69e289defac72018)で対応

2022-11-23 05:00 UTC, Takapy1 commented
@Ayato-kosaka 
レビュー修正終わったので、確認お願いします。

2022-11-23 15:13 UTC, Ayato-kosaka commented
@Takapy1 
tscエラーが出てたから、spelieve-common最新化した

2022-11-23 15:15 UTC, Ayato-kosaka approved these changes

2022-11-23 15:22 UTC, Ayato-kosaka commented
@Takapy1 
確認していい感じだったからマージします！

2022-11-23 15:22 UTC, merged