Fix/place infomation flatlist
Ayato-kosaka/spelieve pull request #391
Opened 2022-12-13 02:48 UTC by Takapy1

@Ayato-kosaka 
修正しました
お願いします。

2022-12-14 22:56 UTC, Ayato-kosaka requested changes
@Takapy1 
ごめん、見逃してた、レビューした！

2022-12-14 22:56 UTC, Ayato-kosaka commented on src/Place/Models/PDB01MPlace/Contexts/PCT012MPlaceOne/ModelComponents/PMC01202PlaceInformation/PlaceInformation.tsx
> +						<View key={day}>
あんまりロジック理解できていないけど、多分dayだと一意にならないよね？（day,time で一意かなと思った）
だから↓みたいにすると良いと思う
```suggestion
						<View key={`${day}${time}`}>
```

2022-12-15 00:48 UTC, Takapy1 commented
@Ayato-kosaka 
dayだと一意になる保証はない

2022-12-15 07:55 UTC, Takapy1 commented
@Ayato-kosaka 
修正したから、問題なければマージしましょう

2022-12-15 07:57 UTC, Ayato-kosaka commented
@Takapy1 ありがとう！マージするわ！

2022-12-15 07:58 UTC, merged