Feature/add admob setting
Ayato-kosaka/spelieve pull request #591
Opened 2023-02-07 09:12 UTC by Takapy1

admob 設定しました！

2023-02-07 09:19 UTC, Takapy1 commented
@Ayato-kosaka 
相談したいこと
- どこに広告を配置するか(現在はHelloSpelieveの一番上に置いている状況)
- 使用した[react-native-google-mobile-ads](https://github.com/invertase/react-native-google-mobile-ads)は、ネイティブのライブラリを使用しているため、`$ expo start `するとエラーになる。(Managed workflowだと使用できないから)
  - expo dev clientなら使用できる
  - react-native-google-mobile-adsがある限り、expo start すると今後エラーがずっと出る状態になっている
  - →開発環境では、読み込まれないという仕組みにしたらいけるのか？（まだよく整理できてない）
- 本番環境のENV末尾に広告用のUnitIDを２つ追加した

2023-02-07 12:43 UTC, Ayato-kosaka commented
@Takapy1 
1てんめは明後日相談しよう
二点目は expo start は使わなくてよくね？って思ってる
Expo webも無理なら要対応

2023-02-09 13:51 UTC, Takapy1 commented
@Ayato-kosaka 
adsenseのコンポーネントもこのプルリクに取り込んでおいた
レビューよろしくです！

2023-02-09 14:58 UTC, Ayato-kosaka requested changes
@Takapy1 
確認したので対応をお願いします！
spelieve-secret の release が変わってなかったから更新しておいた！

2023-02-09 14:58 UTC, Ayato-kosaka commented on src/Common/Components/CCO007GoogleBannerAd/GoogleBannerAd.tsx
> +const adUnitID = __DEV__ ? TestIds.BANNER : ProductionAdUnitID;
```suggestion
const adUnitID = ENV.LOGGER ? TestIds.BANNER : ProductionAdUnitID;
```

2023-02-09 14:58 UTC, Ayato-kosaka commented on src/Common/Components/CCO007GoogleBannerAd/GoogleBannerAd.web.tsx
> +export const GoogleBannerAd = () =>
```suggestion
export const CCO007GoogleBannerAd = () =>
```

2023-02-11 00:41 UTC, Takapy1 commented
@Ayato-kosaka 
修正確認した。マージブロックされているのはなぜや

2023-02-11 07:29 UTC, Ayato-kosaka approved these changes

2023-02-11 07:30 UTC, Ayato-kosaka commented
@Takapy1 
確認したので、 Approve しました！
マージブロックされてたのは、 request change してたから!!
approve したからマージできるようになったからマージお願い！

2023-02-12 03:21 UTC, Takapy1 commented
@Ayato-kosaka 
了解しました。マージします。

2023-02-12 03:21 UTC, merged