Nt/feature typescript
Ayato-kosaka/spelieve pull request #60
Opened 2022-07-01 01:17 UTC by Takapy1

・Typescript導入（Webpack, tscコンパイラ)
・AT0001TimeAreaのts化、リファクタリング
- useEffect１つにした
- propsの型定義

2022-07-01 05:32 UTC, Ayato-kosaka requested changes
@Takapy1 
レビューしました。
不明点あれば気軽に連絡してきてー

2022-07-01 05:32 UTC, Ayato-kosaka commented on src/SV0001Itinerary/Components/atoms/AT0001TimeArea/TimeArea.tsx
> +    span: Date;
spanってのは、名前的に良くないかも
ダイアログから渡される時はspanじゃないから。
Date timeとか、汎用的な名前にしてほしい。

2022-07-01 05:32 UTC, Ayato-kosaka commented on src/SV0001Itinerary/Components/atoms/AT0001TimeArea/TimeArea.tsx
> +    inputProps: {
inputPropsは、inputタグに指定するものだから↓みたいな感じにするべきかと思う

interface Dict {
    [key: string]: string;
}

2022-07-01 05:32 UTC, Ayato-kosaka commented on src/SV0001Itinerary/Components/atoms/AT0001TimeArea/TimeArea.tsx
> +    useEffect(() => {
setTimeは消した？
このままだったら親コンポーネントでspanを変更した場合変更されない気がするんだけど、、、

2022-07-01 05:32 UTC, Ayato-kosaka commented on src/SV0001Itinerary/Components/atoms/AT0002TitleArea/TitleArea.tsx
> +import { StyledInput } from './style'
削除じゃなかったっけ？

2022-07-01 05:32 UTC, Ayato-kosaka commented on src/SV0001Itinerary/Components/atoms/AT0002TitleArea/index.ts
> +import { AT0002TitleArea } from './TitleArea';
削除じゃなかったっけ？

2022-07-02 01:21 UTC, Takapy1 commented on src/SV0001Itinerary/Components/atoms/AT0001TimeArea/TimeArea.tsx
> +    inputProps: {
ちなみにここでinterface使った理由はある？

2022-07-02 01:32 UTC, Takapy1 commented on src/SV0001Itinerary/Components/atoms/AT0001TimeArea/TimeArea.tsx
> +    useEffect(() => {
OGEditablePlanとMCDateTimeどっちでspan変更される？

2022-07-02 03:29 UTC, Ayato-kosaka commented on src/SV0001Itinerary/Components/atoms/AT0001TimeArea/TimeArea.tsx
> +    inputProps: {
@Takapy1 
ごめん、どっかのサイトから引用しただけ。
書き方はよくわかってない
インターフェイスは多分いらない！

2022-07-02 03:42 UTC, Ayato-kosaka commented on src/SV0001Itinerary/Components/atoms/AT0001TimeArea/TimeArea.tsx
> +    useEffect(() => {
@Takapy1 
たしかにどっちだろう、、、
OG0006EditablePlanは外部要因で変更されそうにないよね。

MC0005DateTimeは、既存の開始時間をクリックするとその開始時間で上書きされるからspanが更新されるはず！
どちらにせよ、ATOMの状態変数「time」がprops.spanに依存している以上、useEffectでprops.spanの変更を管理する必要があるっていう整理にはなると思う！

2022-07-02 03:46 UTC, Ayato-kosaka commented
ごめん、renovateのnpm自動アップデートでコンフリクト起きたから↓で解決しておいた
[ef903d0](https://github.com/Ayato-kosaka/react-itinerary/pull/60/commits/ef903d03b18775ea4a04caff68e74af168408972)

2022-08-06 15:41 UTC, Ayato-kosaka reviewed
@Takapy1 
DB0002Itineraries と DB0002ItineraryType のレビューしました。
typescript 歴は野口のほうが長いから、指摘内容に違和感あるところはバシバシ異論言ってきてほしい、議論したい！
ここは、テーブルが増えてもスケルトンにしたい部分だから今のうちに議論はしときたい。

2022-08-06 15:41 UTC, Ayato-kosaka commented on src/SV0001Itinerary/Utils/api/DB0002Itineraries.ts
> +export const read = async (id: string): Promise<DB0002ItineraryType | null> => {
前回の打ち合わせでも話したけど、個人的には↓みたいにしたいんだよね、、、
string の方が可読性が良いなら、itineraryID: string でも良いかもね（DBxxxxhogeで統一できなくなるけど、、、）
```suggestion
export const read = async (id: DB0002ItineraryType['id']): Promise<DB0002ItineraryType | null> => {
```

2022-08-06 15:41 UTC, Ayato-kosaka commented on src/SV0001Itinerary/Utils/api/DB0002Itineraries.ts
> +    }));
↓のように出来ないかな（違和感あればご意見ほしい）
```suggestion
    return (querySnapshot.docs.map((doc): DB0002ItineraryType =>
        doc.data();
     ));
```

2022-08-06 15:41 UTC, Ayato-kosaka commented on src/SV0001Itinerary/Utils/api/DB0002Itineraries.ts
> +import { initItinerary } from 'SV0001Itinerary/Utils/types/DB0002ItineraryType';
↓みたいにして、ドメイン（Itinerary）消せないかな（消せたら9行目以下全コピーでapiファイルは出来るから超楽（一応元のファイルはそうしてた））
```suggestion
import type { DB0002ItineraryType as collectionType } from 'SV0001Itinerary/Utils/types/DB0002ItineraryType';
import { initItinerary as initCollection } from 'SV0001Itinerary/Utils/types/DB0002ItineraryType';
```

2022-08-06 17:22 UTC, Ayato-kosaka commented on src/SV0001Itinerary/Utils/types/DB0002ItineraryType.ts
> +};
あと、DB0002ItinerariesType
って名前にして、機能一覧と統一したい感はある。
コレクション名を複数形にするのやめるのも手かもしれんけど、、、

2022-08-07 12:55 UTC, Takapy1 commented on src/SV0001Itinerary/Utils/api/DB0002Itineraries.ts
> +        };
（メモ用）
3つ目が今のところ理解できてない

2022-08-07 12:56 UTC, Takapy1 commented on src/SV0001Itinerary/Utils/api/DB0002Itineraries.ts
> +export const read = async (id: string): Promise<DB0002ItineraryType | null> => {
知らなかった（勉強不足だった笑）

2022-08-08 12:49 UTC, Takapy1 commented on src/SV0001Itinerary/Utils/types/DB0002ItineraryType.ts
> +};
一つのItineraryの型なのに、複数形にするのが違和感やな

2022-08-08 12:50 UTC, Takapy1 commented on src/SV0001Itinerary/Utils/api/DB0002Itineraries.ts
> +export const read = async (id: string): Promise<DB0002ItineraryType | null> => {
これどうすればいいのかわからなくて一旦このままにしてた

2022-08-08 12:51 UTC, Takapy1 commented on src/SV0001Itinerary/Utils/api/DB0002Itineraries.ts
> +    }));
こっちの方がわかりやすいわ、カラムの数増えた時に
前の記述だと修正だるいから

2022-08-08 14:46 UTC, Takapy1 commented on src/SV0001Itinerary/Utils/api/DB0002Itineraries.ts
> +export const read = async (id: string): Promise<DB0002ItineraryType | null> => {
書けない笑

2022-08-08 14:55 UTC, Takapy1 commented on src/SV0001Itinerary/Utils/types/DB0002ItineraryType.ts
> +};
複数形Typeで対応

2022-08-09 00:47 UTC, Takapy1 commented on src/SV0001Itinerary/Utils/api/DB0002Itineraries.ts
> +        };
@Ayato-kosaka 
対応しました
[9da55dd](https://github.com/Ayato-kosaka/react-itinerary/pull/60/commits/9da55dd1e1ae529ee9abab5f012819029905e753)

2022-08-09 00:52 UTC, Ayato-kosaka commented on src/SV0001Itinerary/Utils/api/DB0002Itineraries.ts
> +        };
@Takapy1 OKです！
気になるポイント三点だけ確認をお願いします。

2022-08-09 00:59 UTC, Takapy1 commented on src/SV0001Itinerary/Utils/api/DB0002Itineraries.ts
> +import { initItinerary } from 'SV0001Itinerary/Utils/types/DB0002ItineraryType';
@Ayato-kosaka 
対応済み
[334c0ac](https://github.com/Ayato-kosaka/react-itinerary/pull/60/commits/334c0acf009b383dc885fb146b15d3b41d489d66)

2022-08-09 01:03 UTC, Takapy1 commented on src/SV0001Itinerary/Utils/types/DB0002ItineraryType.ts
> +};
対応済み
[0dba73b](https://github.com/Ayato-kosaka/react-itinerary/pull/60/commits/0dba73bc7965a7123936200a2dddd692f6e7994e)

2022-08-09 01:04 UTC, Ayato-kosaka commented on src/SV0001Itinerary/Utils/types/DB0002ItineraryType.ts
> +};
OKです

2022-08-09 02:23 UTC, Ayato-kosaka commented
@Takapy1 
指摘対応事項確認しました。
1つ未クローズなので、確認をお願いします。

2022-08-09 02:40 UTC, Takapy1 commented on src/SV0001Itinerary/Utils/api/DB0002Itineraries.ts
> +        };
@Ayato-kosaka 
気になる３点に関して
> ①!docSnap.exists のときって catch してくれる？それともそもそもtypescriptに怒られるかな？
> →catch して null とか返してくれるとありがたい
!docSnap.exists のときに例外ではなく、undefinedとか返るようだったので、try catch→if文に戻した。

> ② docSnap.data()にDB0002ItineraryTypeに含まれないプロパティが含まれた時に除外してくれる？
> 調べた感じ恐らく除外してくれるけど、念の為確認してほしい！
少し面倒なので#110で議論

> ③docSnap.data()にDB0002ItineraryTypeに含まれるプロパティが送られなかったらどうなる？
> →恐らく、idもtitleもnull非許容型だから、エラーとなる
> →createの時点で初期化しているから、エラーとなることはない想定かな？
> そこまで厳しくするべき？は別途議論したいけど、とりあえずOK
init で初期化しているから、エラーになる想定してなかった！
②で対処すれば、解決するかな

2022-08-09 02:56 UTC, Ayato-kosaka commented
@Takapy1 
対応ありがとうー！
とりあえず指摘は全部解決にした！
課題は残ってるけど、apiファイルは軽く横展開して、
Contextに入って下さい！（contextも課題がいっぱい見つかる匂いがしてるからw）

2022-08-09 03:13 UTC, Takapy1 commented
@Ayato-kosaka 
readonlyに関して
IDカラムにしかつけてないんだけど、ItineraryIDにも必要？
ちょいどれにつけるかどうかが理解できてないわ

2022-08-09 03:14 UTC, Ayato-kosaka commented
@Takapy1 
書き換え不可につけるから、ItineraryIDもつけてOK

2022-08-10 04:21 UTC, Takapy1 commented
@Ayato-kosaka 
src/SV0001Itinerary/Hooks/contexts/CT0001PlanGroups.tsx
のchangeRepresentativePlanIDの中のplanのstartTimeってプロパティを参照しているんだけど、
startTimeってカラムあったっけ？

2022-08-10 04:23 UTC, Ayato-kosaka commented
@Takapy1 
あー、、、
DBには登録してないけど、フロントで計算してフロントだけで保持してるやつやなぁー
typescript 絡んでくるとこういうのだるいなぁ
どうしようか、、、

2022-08-10 07:54 UTC, Takapy1 commented
@Ayato-kosaka 
すまん、startTimeがどこで、どういう流れで設定されているのかがわからない

2022-08-10 08:03 UTC, Ayato-kosaka commented
@Takapy1 
StartTimeは、MC0001PlanLogicで、設定されるよ

ロジックとしてまず、
①代表プランはrepresentativeStartTimeで登録される、それ以外は初期値
②代表プランの前後1プランは紐付けられてるプランから計算される、それ以外は初期値
③代表プランの前後2プランは紐付けられてるプランから計算される、それ以外は初期値
・
・
・

2022-08-27 04:14 UTC, closed without merging