代表PLanの滞在時間変更しても自動計算されない
Ayato-kosaka/spelieve pull request #829
Opened 2023-06-18 06:18 UTC by Takapy1

2023-06-18 06:35 UTC, Takapy1 commented
@Ayato-kosaka 
https://github.com/Ayato-kosaka/spelieve/issues/828のバグ修正したので、
レビューおねがします。

2023-06-18 06:45 UTC, Ayato-kosaka requested changes
@Takapy1 
対応ありがとう〜
レビューした！

2023-06-18 06:45 UTC, Ayato-kosaka commented on src/Itinerary/Contexts/ICT031PlansMap/ModelComponents/IMC03101PlanEdit/PlanEditController.ts
あ、そういうことか、、
自分の経路到着時間を計算する時に、自分の経路出発時間＋自分の経路所要時間を監視しないと行けなかったのに、
自分の経路所要時間の監視が漏れてたのか、、
https://github.com/Ayato-kosaka/spelieve/pull/829/files#diff-44225716ed863f498e8e4f51214addc9b2265f9aaa8cfec97f052e56cc1e6c6eR196
このコメントだけ最新化しておいて〜

2023-06-18 22:41 UTC, Takapy1 reviewed
確認済み

2023-06-18 22:42 UTC, Takapy1 commented on src/Itinerary/Contexts/ICT031PlansMap/ModelComponents/IMC03101PlanEdit/PlanEditController.ts
@Ayato-kosaka 
これってもうpushされているから確認したら、resolve conversationすればいいってことよね？

2023-06-19 10:09 UTC, Ayato-kosaka commented on src/Itinerary/Contexts/ICT031PlansMap/ModelComponents/IMC03101PlanEdit/PlanEditController.ts
@Takapy1 
いや、貼ったURLのコメントアウトを最新化して欲しい！

2023-06-19 11:51 UTC, Takapy1 commented on src/Itinerary/Contexts/ICT031PlansMap/ModelComponents/IMC03101PlanEdit/PlanEditController.ts
[8693151](https://github.com/Ayato-kosaka/spelieve/pull/829/commits/869315115eb865614bbde526297dba1cc6a4143a)で対応

2023-06-19 11:51 UTC, Takapy1 commented
@Ayato-kosaka 
コメント最新化した！テストお願いします！

2023-06-19 11:53 UTC, Ayato-kosaka approved these changes
@Takapy1 
ありがとー！
一旦マージするから、develop に入れた状態で打鍵するわー
issue もとりあえずクローズでいいよ！

2023-06-19 11:53 UTC, merged